#!/bin/sh /etc/rc.common

START=99
STOP=10

USE_PROCD=1

start_service() {
    procd_open_instance
    procd_set_param command /overlay/utility/5g_monitor.sh
    procd_set_param respawn
    procd_close_instance
}

stop_service() {
    killall your-script-name 2>/dev/null
}
